// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Buyer struct {
	ID            int32
	Address       pgtype.Text
	PaymentMethod pgtype.Text
	UserID        pgtype.Int4
}

type Category struct {
	ID   int32
	Name string
}

type Farm struct {
	ID           int32
	FarmerID     pgtype.Int4
	Address      pgtype.Text
	Size         pgtype.Float8
	GovernmentID pgtype.Int4
}

type Farmer struct {
	ID     int32
	UserID pgtype.Int4
}

type Product struct {
	ID          int32
	Name        string
	FarmerID    pgtype.Int4
	Price       pgtype.Numeric
	Quantity    int32
	Description pgtype.Text
	Category    pgtype.Int4
}

type User struct {
	ID             int32
	Name           string
	Email          string
	HashedPassword string
	PhoneNumber    string
	IsAdmin        bool
}
